apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
        - name: sonarqube
          image: sonarqube:lts-community
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/sonarqube"
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonarqube-storage
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonarqube-storage
          persistentVolumeClaim:
            claimName: sonarqube-pvc
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-pvc