# Source: ngrok-operator/templates/agent/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngrok-operator-agent
  namespace: ngrok-operator
  labels:
    helm.sh/chart: ngrok-operator-0.20.0
    app.kubernetes.io/name: ngrok-operator
    app.kubernetes.io/instance: ngrok-operator
    app.kubernetes.io/version: "0.18.0"
    app.kubernetes.io/part-of: ngrok-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller